name: Run PyTest

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Google Chrome
      run: |
        sudo apt update
        sudo apt install -y wget curl unzip
        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo apt install -y ./google-chrome-stable_current_amd64.deb

    - name: Install matching ChromeDriver
      run: |
        echo "Detecting Chrome version..."
        CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+')
        echo "Detected Chrome version: $CHROME_VERSION"

        if [ -z "$CHROME_VERSION" ]; then
          echo "❌ Failed to detect Chrome version. Aborting ChromeDriver install."
          exit 1
        fi

        DRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION")
        echo "Resolved matching ChromeDriver version: $DRIVER_VERSION"

        if [ -z "$DRIVER_VERSION" ]; then
          echo "❌ Failed to resolve ChromeDriver version for $CHROME_VERSION"
          exit 1
        fi

        wget -q "https://chromedriver.storage.googleapis.com/$DRIVER_VERSION/chromedriver_linux64.zip"
        unzip chromedriver_linux64.zip
        sudo mv chromedriver /usr/local/bin/
        chmod +x /usr/local/bin/chromedriver
    

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests with Selenium
      run: |
        mkdir -p allure-results
        pytest tests --browser=chrome --headless --alluredir=allure-results

#    - name: Upload Allure results
#      if: always()
#      uses: ./.github/actions/upload-artifact
#      with:
#        name: allure-results
#        path: allure-results

