name: Run PyTest

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install system dependencies and Google Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y wget curl unzip xvfb libnss3 libxi6 libgbm1 libxshmfence1 \
          libxrandr2 libxcomposite1 libxcursor1 libxdamage1 libxss1 fonts-liberation libasound2t64
        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo apt install -y ./google-chrome-stable_current_amd64.deb

    - name: Install matching ChromeDriver
      run: |
        CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+')
        DRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION")
        wget -q "https://chromedriver.storage.googleapis.com/$DRIVER_VERSION/chromedriver_linux64.zip"
        unzip chromedriver_linux64.zip
        sudo mv chromedriver /usr/local/bin/
        chmod +x /usr/local/bin/chromedriver

    - name: Set CHROME_BIN environment variable
      run: echo "CHROME_BIN=$(which google-chrome)" >> $GITHUB_ENV

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests with Selenium
      run: |
        mkdir -p allure-results
        pytest tests --browser=chrome --headless --alluredir=allure-results

#    - name: Upload Allure results
#      if: always()
#      uses: ./.github/actions/upload-artifact
#      with:
#        name: allure-results
#        path: allure-results

